apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model-container
          image: gcr.io/test-project-id/ml-model:latest  # Replace with image 
          ports:
            - containerPort: 8080  
